FORMAT: 1A
HOST: https://lexi.mx/api

# Sessions

Log in and log out users. One account can only have two open sessions.

## Log in [/login]

### Generate, save and send session token [POST]

+ Request (application/json)
  {
    "email": "alexander@thegreat.com",
    "password": "*********"
  }

+ Response 200 (application/json)
  {
    "id": 1,
    "session_token": "d91602ea-5136-48f2-a929-c5d411f5654c"
  }

+ Response 403 (text/plain)
  The user already has two active sessions, they must logout from any of them.
