FORMAT: 1A
HOST: https://lexi.mx/api

# Users

Register and users, edit their information, cancel their accounts.

## Users Collection [/users]

### Register User [POST]
Register new users, receives json.
If the registration is successfull, an email will be send to the user
with an url to verify their account.

+ Request (application/json)
  {
    "username": "thegreat",
    "email": "alexander@thegreat.com",
    "first_name": "Alexander",
    "last_name": "of Macedon",
    "state": "Central Macedonia",
    "accepts_terms": true,
    "accepts_cookies": true,
    "rfc": "OATA200703VE7",
    "legal_name": "Alexander III of Macedon",
    "legal_address": "13 Km Thessaloniki-Perea, Thermi, Central Macedonia, 57001, Greece",
    "legal_email": "alexander@thegreat.com"
  }

+ Response 201 (application/json)
  + Headers
      Location: /users/1
  + Body
      {
        "username": "thegreat",
        "email": "alexander@thegreat.com",
        "first_name": "Alexander",
        "last_name": "of Macedon",
        "state": "Central Macedonia",
        "accepts_terms": true,
        "accepts_cookies": true,
        "rfc": "OATA200703VE7",
        "legal_name": "Alexander III of Macedon",
        "legal_address": "13 Km Thessaloniki-Perea, Thermi, Central Macedonia, 57001, Greece",
        "legal_email": "alexander@thegreat.com"
      }

+ Response 409

## Specific User [/users/{user_id}]

+ Parameters
    + user_id (number) - User ID, integer

### Show User Profile [GET]

+ Response 200
